return {
    starterRecipes = {
        "campfire",
        "flimsy-axe",
        "flimsy-shovel",
        "flimsy-fishing-rod",
        "flimsy-net",
        "flimsy-watering-can",
    },
    inventoryUnlocks = {
        [2] = {
            "wooden-locker",
            "wooden-pendant-light",
            "birdhouse",
        },
        [3] = {
            "ironwood-kitchenette",
            "ironwood-chair",
            "wooden-bookshelf",
        },
        [4] = {
            "golden-axe",
            "golden-shovel",
            "grand-piano",
        },
    },
    stationUnlocks = {
        station_workbench = {
            "log-bench",
            "wooden-simple-bed",
        },
        station_forge = {
            "ironwood-cart",
            "armor-helmet",
        },
        station_cooking = {
            "bread",
            "vegetable-curry",
        },
        station_sewing = {
            "shell-wreath",
            "stacked-wood-wall",
        },
        station_alchemy = {
            "bamboo-wand",
            "shell-wand",
        },
    },
}
