return {
    -- Basic Tools
    leaf = { name = "Leaf", spriteIndex = 1 },
    shovel = { name = "Shovel", spriteIndex = 2 },
    net = { name = "Net", spriteIndex = 3 },
    slingshot = { name = "Slingshot", spriteIndex = 4 },
    fishing_rod = { name = "Fishing Rod", spriteIndex = 5 },
    watering_can = { name = "Watering Can", spriteIndex = 6 },
    axe = { name = "Axe", spriteIndex = 7 },
    stone_axe = { name = "Stone Axe", spriteIndex = 8 },
    pole_vault = { name = "Vaulting Pole", spriteIndex = 9 },
    ladder = { name = "Ladder", spriteIndex = 10 },
    flute = { name = "Pan Flute", spriteIndex = 11 },
    flute_2 = { name = "Flute", spriteIndex = 12 },
    tambourine = { name = "Tambourine", spriteIndex = 13 },

    -- Golden Tools
    golden_axe = { name = "Golden Axe", spriteIndex = 14 },
    golden_net = { name = "Golden Net", spriteIndex = 16 },
    golden_shovel = { name = "Golden Shovel", spriteIndex = 18 },
    golden_can = { name = "Golden Can", spriteIndex = 19 },
    golden_slingshot = { name = "Golden Slingshot", spriteIndex = 17 },
    golden_fishing_rod = { name = "Golden Fishing Rod", spriteIndex = 15 },

    -- Clothing
    glasses_red = { name = "Red Glasses", spriteIndex = 26 },
    shirt_striped = { name = "Striped Shirt", spriteIndex = 27 },
    shirt_blue = { name = "Blue Shirt", spriteIndex = 28 },
    bag_blue = { name = "Bag (Blue)", spriteIndex = 29 },
    socks = { name = "Socks", spriteIndex = 32 },
    shoes_yellow = { name = "Shoes (Yellow)", spriteIndex = 33 },
    shoes_black = { name = "Shoes (Black)", spriteIndex = 34 },
    umbrella_red = { name = "Red Umbrella", spriteIndex = 35 },

    -- Eggs
    egg_purple = { name = "Purple Egg", spriteIndex = 37 },
    egg_orange = { name = "Orange Egg", spriteIndex = 38 },
    egg_yellow = { name = "Yellow Egg", spriteIndex = 41 },
    egg_green = { name = "Green Egg", spriteIndex = 40 },

    -- Currency & UI
    bell_bag_small = { name = "Small Bell Bag", spriteIndex = 20 },
    bell_bag_med = { name = "Bell Bag", spriteIndex = 21 },
    bell_bag_large = { name = "Large Bell Bag", spriteIndex = 22 },
    lost_item = { name = "Lost Item", spriteIndex = 36 },
    bottle_message = { name = "Message Bottle", spriteIndex = 37 },
    recipe_card = { name = "DIY Recipe Card", spriteIndex = 38 },
    paper_gift = { name = "Gift Bag", spriteIndex = 39 },
    leaf_fossil = { name = "Fossil Leaf", spriteIndex = 40 },

    -- Roses
    rose_red = { name = "Red Rose", spriteIndex = 41 },
    rose_white = { name = "White Rose", spriteIndex = 42 },
    rose_pink = { name = "Pink Rose", spriteIndex = 43 },
    rose_yellow = { name = "Yellow Rose", spriteIndex = 261 },

    -- Tulips
    tulip_red = { name = "Red Tulip", spriteIndex = 267 },
    tulip_white = { name = "White Tulip", spriteIndex = 268 },
    tulip_orange = { name = "Orange Tulip", spriteIndex = 273 },

    -- Lilies
    lily_pink = { name = "Pink Lily", spriteIndex = 48 },
    lily_yellow = { name = "Yellow Lily", spriteIndex = 49 },
    lily_white = { name = "White Lily", spriteIndex = 50 },

    -- Mums
    mum_purple = { name = "Purple Mum", spriteIndex = 51 },
    mum_red = { name = "Red Mum", spriteIndex = 52 },
    mum_white = { name = "White Mum", spriteIndex = 53 },

    -- Hyacinths
    hyacinth_blue = { name = "Blue Hyacinth", spriteIndex = 54 },
    hyacinth_pink = { name = "Pink Hyacinth", spriteIndex = 55 },
    hyacinth_orange = { name = "Orange Hyacinth", spriteIndex = 56 },
    hyacinth_white = { name = "White Hyacinth", spriteIndex = 57 },

    -- Cosmos
    cosmos_red = { name = "Red Cosmos", spriteIndex = 58 },
    cosmos_yellow = { name = "Yellow Cosmos", spriteIndex = 59 },
    cosmos_white = { name = "White Cosmos", spriteIndex = 60 },

    -- Fish
    fish_betta = { name = "Betta", spriteIndex = 61 },
    fish_clown = { name = "Clownfish", spriteIndex = 62 },
    fish_puffer = { name = "Pufferfish", spriteIndex = 63 },
    fish_tuna = { name = "Tuna", spriteIndex = 64 },
    fish_bass = { name = "Black Bass", spriteIndex = 65 },
    fish_snapper = { name = "Red Snapper", spriteIndex = 66 },
    fish_goldfish = { name = "Goldfish", spriteIndex = 67 },
    fish_koi = { name = "Koi", spriteIndex = 68 },
    fish_loach = { name = "Loach", spriteIndex = 69 },
    fish_seahorse = { name = "Seahorse", spriteIndex = 70 },

    -- Bugs
    bug_butterfly = { name = "Common Butterfly", spriteIndex = 71 },
    bug_moth = { name = "Moth", spriteIndex = 72 },
    bug_ladybug = { name = "Ladybug", spriteIndex = 73 },
    bug_beetle = { name = "Stag Beetle", spriteIndex = 74 },
    bug_dragonfly = { name = "Dragonfly", spriteIndex = 75 },
    bug_firefly = { name = "Firefly", spriteIndex = 76 },
    bug_spider = { name = "Spider", spriteIndex = 77 },
    bug_scorpion = { name = "Scorpion", spriteIndex = 78 },
    bug_tar = { name = "Tarantula", spriteIndex = 79 },
    bug_cicada = { name = "Cicada", spriteIndex = 80 },

    -- Seasonal
    snowflake = { name = "Snowflake", spriteIndex = 81 },
    ornament_red = { name = "Red Ornament", spriteIndex = 82 },
    ornament_blue = { name = "Blue Ornament", spriteIndex = 83 },
    ornament_gold = { name = "Gold Ornament", spriteIndex = 84 },
    pumpkin_orange = { name = "Orange Pumpkin", spriteIndex = 187 },
    pumpkin_white = { name = "White Pumpkin", spriteIndex = 188 },
    pumpkin_yellow = { name = "Yellow Pumpkin", spriteIndex = 189 },
    pumpkin_green = { name = "Green Pumpkin", spriteIndex = 88 },
    heart_pink = { name = "Heart Crystal", spriteIndex = 494 },

    -- Other
    item_1_up_mushroom = { name = "1-Up Mushroom", spriteIndex = 90 },
    item_2021_celebratory_arch = { name = "2021 celebratory arch", spriteIndex = 91 },
    item_2022_celebratory_arch = { name = "2022 celebratory arch", spriteIndex = 92 },
    block = { name = "? Block", spriteIndex = 93 },
    abd = { name = "ABD", spriteIndex = 94 },
    academic_painting = { name = "academic painting", spriteIndex = 95 },
    academic_painting_fake = { name = "academic painting (fake)", spriteIndex = 96 },
    accessories_stand = { name = "accessories stand", spriteIndex = 97 },
    acnh_nintendo_switch = { name = "ACNH Nintendo Switch", spriteIndex = 98 },
    acorn = { name = "acorn", spriteIndex = 99 },
    acorn_pochette = { name = "acorn pochette", spriteIndex = 100 },
    acorn_rug = { name = "acorn rug", spriteIndex = 101 },
    acoustic_guitar = { name = "acoustic guitar", spriteIndex = 102 },
    afternoon_tea_set = { name = "afternoon-tea set", spriteIndex = 103 },
    agrias_butterfly_model = { name = "agrias butterfly model", spriteIndex = 104 },
    air_circulator = { name = "air circulator", spriteIndex = 105 },
    air_conditioner = { name = "air conditioner", spriteIndex = 106 },
    aji_fry = { name = "aji fry", spriteIndex = 107 },
    aloha_edition_carrying_case = { name = "aloha-edition carrying case", spriteIndex = 108 },
    alto_saxophone = { name = "alto saxophone", spriteIndex = 109 },
    aluminum_briefcase = { name = "aluminum briefcase", spriteIndex = 110 },
    amazing_machine = { name = "amazing machine", spriteIndex = 111 },
    amazing_painting = { name = "amazing painting", spriteIndex = 112 },
    amazing_painting_fake = { name = "amazing painting (fake)", spriteIndex = 113 },
    amp = { name = "amp", spriteIndex = 114 },
    analog_kitchen_scale = { name = "analog kitchen scale", spriteIndex = 115 },
    anatomical_model = { name = "anatomical model", spriteIndex = 116 },
    anchoas_al_ajillo = { name = "anchoas al ajillo", spriteIndex = 117 },
    anchor_statue = { name = "anchor statue", spriteIndex = 118 },
    anchovy = { name = "anchovy", spriteIndex = 119 },
    anchovy_model = { name = "anchovy model", spriteIndex = 120 },
    ancient_statue = { name = "ancient statue", spriteIndex = 121 },
    ancient_statue_fake = { name = "ancient statue (fake)", spriteIndex = 122 },
    angelfish_model = { name = "angelfish model", spriteIndex = 123 },
    angled_signpost = { name = "angled signpost", spriteIndex = 124 },
    ant_farm = { name = "ant farm", spriteIndex = 125 },
    ant_model = { name = "ant model", spriteIndex = 126 },
    anthurium_plant = { name = "anthurium plant", spriteIndex = 127 },
    antique_bed = { name = "antique bed", spriteIndex = 128 },
    antique_bureau = { name = "antique bureau", spriteIndex = 129 },
    antique_cash_register = { name = "antique cash register", spriteIndex = 130 },
    antique_chair = { name = "antique chair", spriteIndex = 131 },
    antique_clock = { name = "antique clock", spriteIndex = 132 },
    antique_console_table = { name = "antique console table", spriteIndex = 133 },
    antique_map = { name = "antique map", spriteIndex = 134 },
    antique_mini_table = { name = "antique mini table", spriteIndex = 135 },
    antique_phone = { name = "antique phone", spriteIndex = 136 },
    antique_radio = { name = "antique radio", spriteIndex = 137 },
    antique_table = { name = "antique table", spriteIndex = 138 },
    antique_vanity = { name = "antique vanity", spriteIndex = 139 },
    antique_wardrobe = { name = "antique wardrobe", spriteIndex = 140 },

    -- Apple Items
    apple = { name = "apple", spriteIndex = 141 },

    -- Other
    apple_chair = { name = "apple chair", spriteIndex = 142 },
    apple_dress = { name = "apple dress", spriteIndex = 143 },
    apple_hat = { name = "apple hat", spriteIndex = 144 },

    -- Apple Items
    apple_jam = { name = "apple jam", spriteIndex = 145 },
    apple_jelly = { name = "apple jelly", spriteIndex = 146 },
    apple_pie = { name = "apple pie", spriteIndex = 147 },

    -- Other
    apple_rug = { name = "apple rug", spriteIndex = 148 },

    -- Apple Items
    apple_smoothie = { name = "apple smoothie", spriteIndex = 149 },
    apple_tart = { name = "apple tart", spriteIndex = 150 },

    -- Other
    apple_umbrella = { name = "apple umbrella", spriteIndex = 151 },
    apple_wall = { name = "apple wall", spriteIndex = 152 },

    -- Materials
    aquarius_fragment = { name = "Aquarius fragment", spriteIndex = 153 },

    -- Other
    aquarius_urn = { name = "Aquarius urn", spriteIndex = 154 },
    arapaima_model = { name = "arapaima model", spriteIndex = 155 },
    arcade_combat_game = { name = "arcade combat game", spriteIndex = 156 },
    arcade_fighting_game = { name = "arcade fighting game", spriteIndex = 157 },
    arcade_mahjong_game = { name = "arcade mahjong game", spriteIndex = 158 },
    arcade_seat = { name = "arcade seat", spriteIndex = 159 },
    arched_reception_counter = { name = "arched reception counter", spriteIndex = 160 },

    -- Materials
    aries_fragment = { name = "Aries fragment", spriteIndex = 161 },

    -- Other
    aries_rocking_chair = { name = "Aries rocking chair", spriteIndex = 162 },

    -- Clothing
    armor_shoes = { name = "armor shoes", spriteIndex = 163 },

    -- Other
    aroma_pot = { name = "aroma pot", spriteIndex = 164 },
    arowana_model = { name = "arowana model", spriteIndex = 165 },
    art_plaque = { name = "art plaque", spriteIndex = 166 },
    artisanal_bug_cage = { name = "artisanal bug cage", spriteIndex = 167 },
    artsy_chair = { name = "artsy chair", spriteIndex = 168 },
    artsy_table = { name = "artsy table", spriteIndex = 169 },
    asteroid = { name = "asteroid", spriteIndex = 170 },
    astronaut_suit = { name = "astronaut suit", spriteIndex = 171 },
    autograph_cards = { name = "autograph cards", spriteIndex = 172 },
    automatic_washer = { name = "automatic washer", spriteIndex = 173 },
    autumn_wall = { name = "autumn wall", spriteIndex = 174 },
    azumaya_gazebo = { name = "azumaya gazebo", spriteIndex = 175 },
    baby_bear = { name = "Baby bear", spriteIndex = 176 },
    baby_bed = { name = "baby bed", spriteIndex = 177 },
    baby_chair = { name = "baby chair", spriteIndex = 178 },
    baby_panda = { name = "Baby panda", spriteIndex = 179 },
    backlit_sign = { name = "backlit sign", spriteIndex = 180 },
    backyard_lawn = { name = "backyard lawn", spriteIndex = 181 },

    -- Clothing
    bagworm_model = { name = "bagworm model", spriteIndex = 182 },

    -- Materials
    baked_potatoes = { name = "baked potatoes", spriteIndex = 183 },

    -- Other
    ball = { name = "ball", spriteIndex = 184 },
    ball_catcher = { name = "ball catcher", spriteIndex = 185 },

    -- Materials
    bamboo_basket = { name = "bamboo basket", spriteIndex = 186 },
    bamboo_bench = { name = "bamboo bench", spriteIndex = 187 },
    bamboo_candleholder = { name = "bamboo candleholder", spriteIndex = 188 },
    bamboo_doll = { name = "bamboo doll", spriteIndex = 189 },
    bamboo_drum = { name = "bamboo drum", spriteIndex = 190 },
    bamboo_floor_lamp = { name = "bamboo floor lamp", spriteIndex = 191 },

    -- Cherry Items
    cherry = { name = "Cherry", spriteIndex = 192 },

    -- Materials
    bamboo_flooring = { name = "bamboo flooring", spriteIndex = 193 },
    bamboo_grass = { name = "bamboo grass", spriteIndex = 194 },
    bamboo_hat = { name = "bamboo hat", spriteIndex = 194 },
    bamboo_lattice_fence = { name = "bamboo lattice fence", spriteIndex = 195 },
    bamboo_lunch_box = { name = "bamboo lunch box", spriteIndex = 196 },
    bamboo_noodle_slide = { name = "bamboo noodle slide", spriteIndex = 197 },
    bamboo_partition = { name = "bamboo partition", spriteIndex = 198 },
    bamboo_piece = { name = "bamboo piece", spriteIndex = 199 },
    bamboo_shelf = { name = "bamboo shelf", spriteIndex = 200 },
    bamboo_shoot = { name = "bamboo shoot", spriteIndex = 201 },
    bamboo_speaker = { name = "bamboo speaker", spriteIndex = 202 },
    bamboo_sphere = { name = "bamboo sphere", spriteIndex = 203 },
    bamboo_stool = { name = "bamboo stool", spriteIndex = 204 },
    bamboo_stopblock = { name = "bamboo stopblock", spriteIndex = 205 },
    bamboo_wall = { name = "bamboo wall", spriteIndex = 206 },
    bamboo_wall_decoration = { name = "bamboo wall decoration", spriteIndex = 207 },
    bamboo_wand = { name = "bamboo wand", spriteIndex = 208 },
    bamboo_grove_wall = { name = "bamboo-grove wall", spriteIndex = 209 },
    bamboo_shoot_lamp = { name = "bamboo-shoot lamp", spriteIndex = 210 },
    bamboo_shoot_soup = { name = "bamboo-shoot soup", spriteIndex = 211 },
    bamboo_slats_fence = { name = "bamboo-slats fence", spriteIndex = 212 },

    -- Other
    banker_s_lamp = { name = "banker's lamp", spriteIndex = 213 },
    baobab = { name = "baobab", spriteIndex = 214 },
    barbecue = { name = "barbecue", spriteIndex = 215 },
    barbed_wire_fence = { name = "barbed-wire fence", spriteIndex = 216 },
    barbell = { name = "barbell", spriteIndex = 217 },
    barred_knifejaw = { name = "barred knifejaw", spriteIndex = 218 },
    barred_knifejaw_model = { name = "barred knifejaw model", spriteIndex = 219 },
    barred_knifejaw_carpaccio = { name = "barred-knifejaw carpaccio", spriteIndex = 220 },
    barrel = { name = "barrel", spriteIndex = 221 },
    barreleye_model = { name = "barreleye model", spriteIndex = 222 },
    baseball_set = { name = "baseball set", spriteIndex = 223 },
    basement_flooring = { name = "basement flooring", spriteIndex = 224 },
    basic_painting = { name = "basic painting", spriteIndex = 225 },
    basic_painting_fake = { name = "basic painting (fake)", spriteIndex = 226 },
    basic_school_chair = { name = "basic school chair", spriteIndex = 227 },
    basic_teacher_s_desk = { name = "basic teacher's desk", spriteIndex = 228 },
    basket_pack = { name = "basket pack", spriteIndex = 229 },
    basketball_hoop = { name = "basketball hoop", spriteIndex = 230 },
    bath_bucket = { name = "bath bucket", spriteIndex = 231 },
    bath_stool = { name = "bath stool", spriteIndex = 232 },
    bathroom_sink = { name = "bathroom sink", spriteIndex = 233 },
    bathroom_stall = { name = "bathroom stall", spriteIndex = 234 },
    bathroom_towel_rack = { name = "bathroom towel rack", spriteIndex = 235 },
    bathtub_with_yuzu = { name = "bathtub with yuzu", spriteIndex = 236 },
    beach_ball = { name = "beach ball", spriteIndex = 237 },
    beekeeper_s_hive = { name = "beekeeper's hive", spriteIndex = 238 },
    big_festive_tree = { name = "big festive tree", spriteIndex = 239 },
    birdbath = { name = "birdbath", spriteIndex = 240 },
    birdcage = { name = "birdcage", spriteIndex = 241 },
    birdhouse = { name = "birdhouse", spriteIndex = 242 },
    block_fence = { name = "block fence", spriteIndex = 243 },
    blossom_viewing_lantern = { name = "blossom-viewing lantern", spriteIndex = 244 },

    -- Seasonal
    blue_ornament = { name = "blue ornament", spriteIndex = 245 },

    -- Roses
    blue_rose_crown = { name = "blue rose crown", spriteIndex = 246 },
    blue_rose_wreath = { name = "blue rose wreath", spriteIndex = 247 },
    blue_roses = { name = "blue roses", spriteIndex = 248 },

    -- Other
    bone_doorplate = { name = "bone doorplate", spriteIndex = 249 },
    bonfire = { name = "bonfire", spriteIndex = 250 },
    bonsai_shelf = { name = "bonsai shelf", spriteIndex = 251 },
    boomerang = { name = "boomerang", spriteIndex = 252 },
    box_shaped_seat = { name = "box-shaped seat", spriteIndex = 253 },
    bread = { name = "bread", spriteIndex = 254 },
    bread_gratin = { name = "bread gratin", spriteIndex = 255 },
    brick_fence = { name = "brick fence", spriteIndex = 256 },
    brick_oven = { name = "brick oven", spriteIndex = 257 },
    brick_pillar = { name = "brick pillar", spriteIndex = 258 },
    brick_well = { name = "brick well", spriteIndex = 259 },
    bridge_construction_kit = { name = "bridge construction kit", spriteIndex = 260 },
    brown_herringbone_wall = { name = "brown herringbone wall", spriteIndex = 261 },

    -- Materials
    brown_sugar = { name = "brown sugar", spriteIndex = 262 },

    -- Other
    campfire = { name = "campfire", spriteIndex = 263 },

    -- Cherry Blossom
    cherry_blossom_bonsai = { name = "cherry-blossom bonsai", spriteIndex = 264 },
    cherry_blossom_petal = { name = "cherry-blossom petal", spriteIndex = 265 },

    -- Materials
    clay = { name = "clay", spriteIndex = 266 },
    clump_of_weeds = { name = "clump of weeds", spriteIndex = 267 },

    -- Flimsy Tools
    flimsy_axe = { name = "flimsy axe", spriteIndex = 268 },
    flimsy_shovel = { name = "flimsy shovel", spriteIndex = 269 },

    -- Materials
    flour = { name = "flour", spriteIndex = 270 },
    gold_nugget = { name = "gold nugget", spriteIndex = 271 },

    -- Seasonal
    gold_ornament = { name = "gold ornament", spriteIndex = 272 },

    -- Materials
    hardwood = { name = "hardwood", spriteIndex = 273 },

    -- Other
    horse_mackerel = { name = "horse mackerel", spriteIndex = 274 },

    -- Materials
    iron_nugget = { name = "iron nugget", spriteIndex = 275 },

    -- Other
    log_stakes = { name = "log stakes", spriteIndex = 276 },

    -- Materials
    maple_leaf = { name = "maple leaf", spriteIndex = 277 },

    -- Other
    pine_bonsai_tree = { name = "pine bonsai tree", spriteIndex = 278 },

    -- Materials
    potato = { name = "potato", spriteIndex = 279 },

    -- Seasonal
    red_ornament = { name = "red ornament", spriteIndex = 280 },

    -- Materials
    softwood = { name = "softwood", spriteIndex = 281 },
    star_fragment = { name = "star fragment", spriteIndex = 282 },
    stone = { name = "stone", spriteIndex = 283 },
    sugar = { name = "sugar", spriteIndex = 284 },
    sugarcane = { name = "sugarcane", spriteIndex = 285 },
    wasp_nest = { name = "wasp nest", spriteIndex = 286 },
    whole_wheat_flour = { name = "whole-wheat flour", spriteIndex = 287 },
    wood = { name = "wood", spriteIndex = 288 },
    young_spring_bamboo = { name = "young spring bamboo", spriteIndex = 289 },
}
